config/routes.rb
Rails.application.routes.draw do
  #get 'relationships/followings' 消したやつ！
  #get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  resources :messages, only: [:show, :create]

  #post 'follow/:id' => 'relationships#follow', as: 'follow'
  #post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  #def followings
    #@user = User.find(params[:id])
   # @users = @user.following_user
  #end

  #def followers
    #@user = User.find(params[:id])
    #@users = @user.follower_user
  #end

#  def follow
#    current_user.follow(params[:id])
#    redirect_to request.referer
#  end

#  def unfollow
#    current_user.unfollow(params[:id])
#    redirect_to request.referer
#  end



  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end




end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<!--フォロー機能-->
  <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <!--%= link_to "フォロー外す", unfollow_path(user.id), method: :post %-->
      <%= link_to "フォロー外す", user_relationships_path(user.id), class: "btn btn-sm btn-danger", method: :delete %>
    <% else %>
      <!--%= link_to "フォローする", follow_path(user.id), method: :post %-->
      <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-sm btn-success", method: :post %>
    <% end %>
  <% end %>

app/views/relationships/followers.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
      </tbody>
    </table>
    <% end %>
  <% else %>
  <p>ユーザーはいません</p>



<% end %>

app/views/relationships/followings.html.erb
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user %></td>
        </tr>
      </tbody>
    </table>
    <% end %>
  <% else %>
  <p>ユーザーはいません</p>



<% end %>